version: '3.3'
services:
    wordpress:
        image: wordpress:mine
        build:
          context: ./requirements/wordpress/
          args:
            PHP_VERSION: 7.3
        container_name: wordpress
        depends_on:
          - mariadb
        networks:
          - network
        env_file:
          - ".env"
        volumes:
          - "wp:/var/www/html/wordpress"
        restart: always

    nginx:
        image: nginx:mine
        build:
          context: ./requirements/nginx/
          args:
            DOMAIN_NAME: zkansoun.42.fr
            LOGIN: zkansoun
        container_name: nginx
        depends_on:
          - wordpress
        networks:
          - network
        ports:
          - "443:443"
        volumes:
          - "wp:/var/www/html/wordpress"
        restart: always

    mariadb:
        image: mariadb:mine
        env_file:
        - ".env"
        build: ./requirements/mariadb/
        container_name: mariadb
        networks:
        - network
        volumes:
        - "db:/var/lib/mysql"
        restart: always

networks:
  network:

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/zkansoun/data/wp
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/zkansoun/data/db
      o: bind
